### Get all users

GET http://localhost:3000/all-users

##### Get user by ID.

GET http://localhost:3000/users/12

#### Create user 

POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "Pepe Test3",
	"password": "0000abc",
	"email": "pepe3@gmail.com"
}

### Delete User by ID.

DELETE http://localhost:3000/user/12

### Edit User Information

PUT http://localhost:3000/users-info/13
Content-Type: application/json

{
    "username": "Pepe TripleInfinito infinito infinito",
	"password": "0000abc",
	"email": "pepeMasInfinito@gmail.com"
}