### Obtener lista de intereses
GET http://localhost:4000/api/interests

### Crear interest
POST http://localhost:4000/api/interests
Content-Type: application/json

{
	"name": "Restaurant"
}

### Eliminar por ID
DELETE http://localhost:4000/api/interests/5

### Actualizar por ID 
PUT http://localhost:4000/api/interests/1
Content-Type: application/json

{
	"name": "Fresh Air"
}

### Relate user-insterests
POST http://localhost:4000/api/users/1/interests
Content-Type: application/json

{
	"interests_id": [1, 2, 3, 4]
}