### OBTENER TODOS LOS POIS
GET http://localhost:4000/api/pois

### CREAR POI
POST http://localhost:4000/api/pois
Content-Type: application/json

{
	"name": "Bike Park CacaoCycling",
	"address": "JVH9+JV Cacao Cycling, Mérida 5101, Mérida",
	"lat": 8.6286146,
	"lng": -71.1340762,
	"category": "Park",
	"open_time": "09:00:00",
	"close_time": "17:00:00",
	"average_stay_minutes": 120
}

### ELIMINAR POI 
DELETE http://localhost:4000/api/pois/3

### ACTUALIZAR POI DATA
PATCH http://localhost:4000/api/pois/2
Content-Type: application/json

{
}