
### OBTENER TODOS LOS TRIPS
GET http://localhost:3000/trips

### OBTENER TRIP DETAILS por ID including stops details.
GET http://localhost:3000/trips/1

### CREATE A TRIP
POST http://localhost:3000/users/1/trips
Content-Type: application/json

{
  "title": "Medellín",
  "lat": 6.2454982,
  "lng": -75.575423,
  "arrive_date": "2026-02-11T14:00:00Z",
  "leave_date": "2026-02-20T10:00:00Z"
}


### ELIMINAR TRIP por ID
DELETE http://localhost:3000/trips/3
