
### OBTENER TODOS LOS TRIPS
GET http://localhost:4000/api/trips

### OBTENER TRIP DETAILS por ID including stops details.
GET http://localhost:4000/api/trips/1

### CREATE A TRIP
POST http://localhost:4000/api/users/1/trips
Content-Type: application/json

{
  "title": "Merida",
  "lat": 8.5718775,
  "lng": -71.1800371,
  "arrive_date": "2026-02-11T14:00:00Z",
  "leave_date": "2026-02-20T10:00:00Z"
}


### ELIMINAR TRIP por ID
DELETE http://localhost:4000/api/trips/4
